#

rule run_metabolomics_elastic_net:
    output:
        'results/elastic_net_metabolomics.positive_features.tsv',
        'results/elastic_net_metabolomics.negative_features.tsv'    
    run:
        cmd='python regression_hospital_free.py raw_data/2020-06-11_metabolomics.tsv -a elastic_net -o results/elastic_net_metabolomics'
        shell('echo "{}"'.format(cmd))
        shell(cmd)

rule run_metabolomics_elastic_net_remove_unknown:
    output:
        'results/elastic_net_metabolomics_remove_unknowns.positive_features.tsv',
        'results/elastic_net_metabolomics_remove_unknowns.negative_features.tsv'
    run:
        cmd='python regression_hospital_free.py raw_data/2020-06-11_metabolomics.tsv -a elastic_net -r -o results/elastic_net_metabolomics_remove_unknowns'
        shell('echo "{}"'.format(cmd))
        shell(cmd)

rule run_proteomics_elastic_net:
    output:
        'results/elastic_net_proteomics.positive_features.tsv',
        'results/elastic_net_proteomics.negative_features.tsv'
    run:
        cmd='python regression_hospital_free.py raw_data/2020-06-10_proteomics.tsv -a elastic_net -o results/elastic_net_proteomics'
        shell('echo "{}"'.format(cmd))
        shell(cmd)

rule run_lipidomics_elastic_net:
    output:
        'results/elastic_net_lipidomics.positive_features.tsv',
        'results/elastic_net_lipidomics.negative_features.tsv'
    run:
        cmd='python regression_hospital_free.py raw_data/2020-06-10_lipidomics.tsv -a elastic_net -o results/elastic_net_lipidomics'
        shell('echo "{}"'.format(cmd))
        shell(cmd)

rule run_lipidomics_elastic_net_remove_unknown:
    output:
        'results/elastic_net_lipidomics_remove_unknowns.positive_features.tsv',
        'results/elastic_net_lipidomics_remove_unknowns.negative_features.tsv'
    run:
        cmd='python regression_hospital_free.py raw_data/2020-06-10_lipidomics.tsv -a elastic_net -r -o results/elastic_net_lipidomics_remove_unknowns'
        shell('echo "{}"'.format(cmd))
        shell(cmd)
